const router = require('express').Router()
const UserController = require('../Controllers/userController')
const sessionChecker = require('../middlewares/sessionChecker')
const userLogin = require('../middlewares/userLogin')
router.get('/register',UserController.createUser)
router.post('/register',UserController.createUserPost)
router.get('/login',sessionChecker,UserController.loginUser)
router.post('/login',UserController.loginUserPost)
router.get('/dashboard',userLogin,UserController.dashboard)
router.get('/logout',userLogin,UserController.logout)
router.get('/balance/:id',userLogin,UserController.balancePage)
router.post('/balance/:id',userLogin,UserController.balancePagePost)
router.get('/cart',userLogin,UserController.addToCart)
router.get('/cart/delete/:shoesUserId',userLogin,UserController.delete)
router.get('/cart/increase/:shoesUserId',userLogin,UserController.increaseQuantity)
router.get('/cart/decrease/:shoesUserId',userLogin,UserController.decreaseQuantity)
module.exports = router